version: "3"
services:
  web:
    image: aleksandrlytysov/eth-truffle:alpha
    ports:
      - "8085:80"
    networks:
      - webnet
  etherium:
    image: desmart/testrpc:latest
    ports:
      - "8545:8545"
    networks:
      - webnet
  truffle:
    image: desmart/testrpc:latest
networks:
  webnet:
